# -*- coding: utf-8 -*-
"""print1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15DTzZvU_zpezcsivxIxLrPXr1xdvlyuA
"""
def print1():
    print('와...폼미쳤네..?')
    
