# -*- coding: utf-8 -*-
"""print2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15DTzZvU_zpezcsivxIxLrPXr1xdvlyuA
"""
def print2() :
    print('빅뉴스다 이거...!)